In [6]:
import tensorflow as tf
from data_utils_new import *
from trainer_new import *
from network_new import *
%load_ext autoreload
%autoreload 2
   
#device = '/device:GPU:0'   # Change this to a CPU/GPU as you wish!
device = '/cpu:0'        # Change this to a CPU/GPU as you wish!
num_epochs = 10
channel_1, channel_2, channel_3, num_classes = 32, 64, 128, 10
model = MyFirstNet(channel_1, channel_2, channel_3, num_classes)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
def model_init_fn():
    return MyFirstNet(channel_1, channel_2, channel_3, num_classes)

def optimizer_init_fn():
    learning_rate = 1e-3
    return tf.keras.optimizers.Adam(learning_rate) 

train_part34(model_init_fn, optimizer_init_fn, num_epochs=num_epochs, device = device)

(49000, 32, 32, 3)
Epoch 1, Loss: 1.613469123840332, Accuracy: 41.422447204589844, Val Loss: 1.3672999143600464, Val Accuracy: 50.5
Epoch 2, Loss: 1.1818236112594604, Accuracy: 57.83061218261719, Val Loss: 1.2401325702667236, Val Accuracy: 54.900001525878906
Epoch 3, Loss: 1.026139736175537, Accuracy: 63.744895935058594, Val Loss: 1.1653940677642822, Val Accuracy: 57.70000076293945
Epoch 4, Loss: 0.9317013621330261, Accuracy: 67.20612335205078, Val Loss: 1.1028639078140259, Val Accuracy: 59.974998474121094
Epoch 5, Loss: 0.8677606582641602, Accuracy: 69.44693756103516, Val Loss: 1.0763531923294067, Val Accuracy: 60.81999969482422
Epoch 6, Loss: 0.8128721714019775, Accuracy: 71.5346908569336, Val Loss: 1.053977131843567, Val Accuracy: 61.633331298828125
Epoch 7, Loss: 0.7693241834640503, Accuracy: 72.85102081298828, Val Loss: 1.028766393661499, Val Accuracy: 62.71428298950195
Epoch 8, Loss: 0.7239751815795898, Accuracy: 74.77143096923828, Val Loss: 1.0065616369247437, Val Accuracy: 63.6

In [25]:
layer = tf.keras.layers.Dense(10, input_shape = (None, 4))
layer(tf.zeros((10, 4)))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [26]:
layer.variables

[<tf.Variable 'dense_24/kernel:0' shape=(4, 10) dtype=float32, numpy=
 array([[ 0.48721683,  0.4693085 , -0.56703055, -0.0822233 ,  0.07910419,
         -0.00218594, -0.46565196, -0.1265881 , -0.5781083 ,  0.31809258],
        [-0.47842443,  0.6073866 ,  0.13130164,  0.46094084, -0.5790156 ,
          0.19877082, -0.3438412 , -0.07026577, -0.02362621, -0.54595315],
        [-0.5816148 , -0.5344955 ,  0.1915124 , -0.046377  ,  0.43482602,
         -0.22756729, -0.3843923 ,  0.5925398 , -0.4360845 ,  0.19022942],
        [-0.4297785 , -0.6086211 ,  0.06351382,  0.38706005,  0.02193618,
         -0.40611482,  0.48249912,  0.3310948 ,  0.46016896, -0.02742773]],
       dtype=float32)>,
 <tf.Variable 'dense_24/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [28]:
layer.kernel, layer.bias

(<tf.Variable 'dense_24/kernel:0' shape=(4, 10) dtype=float32, numpy=
 array([[ 0.48721683,  0.4693085 , -0.56703055, -0.0822233 ,  0.07910419,
         -0.00218594, -0.46565196, -0.1265881 , -0.5781083 ,  0.31809258],
        [-0.47842443,  0.6073866 ,  0.13130164,  0.46094084, -0.5790156 ,
          0.19877082, -0.3438412 , -0.07026577, -0.02362621, -0.54595315],
        [-0.5816148 , -0.5344955 ,  0.1915124 , -0.046377  ,  0.43482602,
         -0.22756729, -0.3843923 ,  0.5925398 , -0.4360845 ,  0.19022942],
        [-0.4297785 , -0.6086211 ,  0.06351382,  0.38706005,  0.02193618,
         -0.40611482,  0.48249912,  0.3310948 ,  0.46016896, -0.02742773]],
       dtype=float32)>,
 <tf.Variable 'dense_24/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [29]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
        
    def build(self, input_shape):
        self.kernel = self.add_weight("kernel", shape = [int(input_shape[-1]), self.num_outputs])
        
    def call(self, input):
        return tf.matmul(input, self.kernel)
    
layer = MyDenseLayer(10)

_ = layer(tf.zeros((10, 5)))

In [30]:
layer.trainable_variables

[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.36101952,  0.3891167 ,  0.3790403 , -0.16709897, -0.07070893,
         -0.08277947,  0.25023758,  0.37144202,  0.54409343,  0.5742951 ],
        [ 0.16722107, -0.06229872,  0.15400505,  0.22881061,  0.5440286 ,
          0.26932526, -0.29787055, -0.5611146 , -0.1429644 , -0.37048155],
        [ 0.47519296,  0.4327882 ,  0.33073413,  0.38190788, -0.27237782,
         -0.11693835, -0.37990195, -0.56716007, -0.3069636 ,  0.3221699 ],
        [ 0.6088987 , -0.1764512 , -0.5215313 ,  0.22983974,  0.5330886 ,
          0.27226955,  0.32410377, -0.5332144 , -0.26928046,  0.26926297],
        [ 0.3989789 ,  0.03922027,  0.02071059,  0.410919  , -0.03417486,
         -0.21777993,  0.39279634, -0.11439878,  0.5731495 , -0.30182844]],
       dtype=float32)>]

In [31]:
print([var.name for var in layer.trainable_variables])

['my_dense_layer/kernel:0']


In [46]:
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResnetIdentityBlock, self).__init__()
        filter1, filter2, filter3 = filters
        
        self.conv2a = tf.keras.layers.Conv2D(filter1, (1,1))
        self.bn2a = tf.keras.layers.BatchNormalization()
        
        self.conv2b = tf.keras.layers.Conv2D(filter2, kernel_size, padding='same')
        self.bn2b = tf.keras.layers.BatchNormalization()
        
        self.conv2c = tf.keras.layers.Conv2D(filter3, (1, 1))
        self.bn2c = tf.keras.layers.BatchNormalization()
        
    def call(self, input_tensor, training = False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training = training)
        x = tf.nn.relu(x)
        
        x = self.conv2b(x)
        x = self.bn2b(x, training = training)
        x = tf.nn.relu(x)
        
        x = self.conv2c(x)
        x = self.bn2c(x, training = training)
        
        x += input_tensor
        return tf.nn.relu(x)
    
block = ResnetIdentityBlock((1,1), [1, 2, 3])

In [47]:
outputs = block(tf.zeros([1, 2, 3, 3])) 
print(outputs)

(1, 2, 3, 1)
(1, 2, 3, 1)
(1, 2, 3, 2)
(1, 2, 3, 3)
tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)


In [35]:
block.layers

In [36]:
len(block.variables)

18

In [37]:
block.summary()

Model: "resnet_identity_block_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_21 (Conv2D)           multiple                  4         
_________________________________________________________________
batch_normalization_21 (Batc multiple                  4         
_________________________________________________________________
conv2d_22 (Conv2D)           multiple                  4         
_________________________________________________________________
batch_normalization_22 (Batc multiple                  8         
_________________________________________________________________
conv2d_23 (Conv2D)           multiple                  9         
_________________________________________________________________
batch_normalization_23 (Batc multiple                  12        
Total params: 41
Trainable params: 29
Non-trainable params: 12
______________________________________________